name: apricots
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8.8
  - numpy>=1.20.1
  - h5py>=2.10.0
  - more-itertools>=8.7.0
  - backports.functools_lru_cache>=1.6.4
  - matplotlib>=3.3.4
  - scipy>=1.6.2
  - jupyter>=1.0.0
